"forecast": {
    "forecastday": [
        {
            "date": "2023-06-06",
            "date_epoch": 1686009600,
            "day": {
                "maxtemp_c": 32.9,
                "maxtemp_f": 91.2,
                "mintemp_c": 17.2,
                "mintemp_f": 63.0,
                "avgtemp_c": 24.3,
                "avgtemp_f": 75.7,
                "maxwind_mph": 6.3,
                "maxwind_kph": 10.1,
                "totalprecip_mm": 0.0,
                "totalprecip_in": 0.0,
                "totalsnow_cm": 0.0,
                "avgvis_km": 10.0,
                "avgvis_miles": 6.0,
                "avghumidity": 68.0,
                "daily_will_it_rain": 0,
                "daily_chance_of_rain": 0,
                "daily_will_it_snow": 0,
                "daily_chance_of_snow": 0,
                "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                },
                "uv": 6.0
            },
            "astro": {
                "sunrise": "06:07 AM",
                "sunset": "08:39 PM",
                "moonrise": "11:49 PM",
                "moonset": "08:18 AM",
                "moon_phase": "Waning Gibbous",
                "moon_illumination": "95",
                "is_moon_up": 0,
                "is_sun_up": 1
            },
            "hour": [
                {
                    "time_epoch": 1686027600,
                    "time": "2023-06-06 00:00",
                    "temp_c": 20.0,
                    "temp_f": 68.0,
                    "is_day": 0,
                    "condition": {
                        "text": "Clear",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                        "code": 1000
                    },
                    "wind_mph": 6.3,
                    "wind_kph": 10.1,
                    "wind_degree": 133,
                    "wind_dir": "SE",
                    "pressure_mb": 1015.0,
                    "pressure_in": 29.96,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 82,
                    "cloud": 10,
                    "feelslike_c": 20.0,
                    "feelslike_f": 68.0,
                    "windchill_c": 20.0,
                    "windchill_f": 68.0,
                    "heatindex_c": 20.0,
                    "heatindex_f": 68.0,
                    "dewpoint_c": 16.8,
                    "dewpoint_f": 62.2,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 13.2,
                    "gust_kph": 21.2,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686031200,
                    "time": "2023-06-06 01:00",
                    "temp_c": 18.9,
                    "temp_f": 66.0,
                    "is_day": 0,
                    "condition": {
                        "text": "Clear",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                        "code": 1000
                    },
                    "wind_mph": 6.3,
                    "wind_kph": 10.1,
                    "wind_degree": 145,
                    "wind_dir": "SE",
                    "pressure_mb": 1015.0,
                    "pressure_in": 29.97,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 85,
                    "cloud": 11,
                    "feelslike_c": 18.9,
                    "feelslike_f": 66.0,
                    "windchill_c": 18.9,
                    "windchill_f": 66.0,
                    "heatindex_c": 18.9,
                    "heatindex_f": 66.0,
                    "dewpoint_c": 16.4,
                    "dewpoint_f": 61.5,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 12.5,
                    "gust_kph": 20.2,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686034800,
                    "time": "2023-06-06 02:00",
                    "temp_c": 18.5,
                    "temp_f": 65.3,
                    "is_day": 0,
                    "condition": {
                        "text": "Clear",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                        "code": 1000
                    },
                    "wind_mph": 3.6,
                    "wind_kph": 5.8,
                    "wind_degree": 191,
                    "wind_dir": "SSW",
                    "pressure_mb": 1015.0,
                    "pressure_in": 29.97,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 86,
                    "cloud": 9,
                    "feelslike_c": 18.5,
                    "feelslike_f": 65.3,
                    "windchill_c": 18.5,
                    "windchill_f": 65.3,
                    "heatindex_c": 18.5,
                    "heatindex_f": 65.3,
                    "dewpoint_c": 16.1,
                    "dewpoint_f": 61.0,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 7.4,
                    "gust_kph": 11.9,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686038400,
                    "time": "2023-06-06 03:00",
                    "temp_c": 18.3,
                    "temp_f": 64.9,
                    "is_day": 0,
                    "condition": {
                        "text": "Clear",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                        "code": 1000
                    },
                    "wind_mph": 2.7,
                    "wind_kph": 4.3,
                    "wind_degree": 0,
                    "wind_dir": "N",
                    "pressure_mb": 1015.0,
                    "pressure_in": 29.96,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 87,
                    "cloud": 7,
                    "feelslike_c": 18.3,
                    "feelslike_f": 64.9,
                    "windchill_c": 18.3,
                    "windchill_f": 64.9,
                    "heatindex_c": 18.3,
                    "heatindex_f": 64.9,
                    "dewpoint_c": 16.0,
                    "dewpoint_f": 60.8,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 5.6,
                    "gust_kph": 9.0,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686042000,
                    "time": "2023-06-06 04:00",
                    "temp_c": 17.8,
                    "temp_f": 64.0,
                    "is_day": 0,
                    "condition": {
                        "text": "Clear",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                        "code": 1000
                    },
                    "wind_mph": 5.6,
                    "wind_kph": 9.0,
                    "wind_degree": 11,
                    "wind_dir": "NNE",
                    "pressure_mb": 1015.0,
                    "pressure_in": 29.96,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 89,
                    "cloud": 6,
                    "feelslike_c": 17.8,
                    "feelslike_f": 64.0,
                    "windchill_c": 17.8,
                    "windchill_f": 64.0,
                    "heatindex_c": 17.8,
                    "heatindex_f": 64.0,
                    "dewpoint_c": 15.9,
                    "dewpoint_f": 60.6,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 11.4,
                    "gust_kph": 18.4,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686045600,
                    "time": "2023-06-06 05:00",
                    "temp_c": 17.4,
                    "temp_f": 63.3,
                    "is_day": 0,
                    "condition": {
                        "text": "Clear",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                        "code": 1000
                    },
                    "wind_mph": 6.0,
                    "wind_kph": 9.7,
                    "wind_degree": 7,
                    "wind_dir": "N",
                    "pressure_mb": 1014.0,
                    "pressure_in": 29.96,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 90,
                    "cloud": 6,
                    "feelslike_c": 17.4,
                    "feelslike_f": 63.3,
                    "windchill_c": 17.4,
                    "windchill_f": 63.3,
                    "heatindex_c": 17.4,
                    "heatindex_f": 63.3,
                    "dewpoint_c": 15.7,
                    "dewpoint_f": 60.3,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 12.5,
                    "gust_kph": 20.2,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686049200,
                    "time": "2023-06-06 06:00",
                    "temp_c": 17.2,
                    "temp_f": 63.0,
                    "is_day": 0,
                    "condition": {
                        "text": "Clear",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                        "code": 1000
                    },
                    "wind_mph": 5.4,
                    "wind_kph": 8.6,
                    "wind_degree": 15,
                    "wind_dir": "NNE",
                    "pressure_mb": 1015.0,
                    "pressure_in": 29.96,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 90,
                    "cloud": 7,
                    "feelslike_c": 17.2,
                    "feelslike_f": 63.0,
                    "windchill_c": 17.2,
                    "windchill_f": 63.0,
                    "heatindex_c": 17.2,
                    "heatindex_f": 63.0,
                    "dewpoint_c": 15.5,
                    "dewpoint_f": 59.9,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 11.2,
                    "gust_kph": 18.0,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686052800,
                    "time": "2023-06-06 07:00",
                    "temp_c": 17.7,
                    "temp_f": 63.9,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 4.9,
                    "wind_kph": 7.9,
                    "wind_degree": 62,
                    "wind_dir": "ENE",
                    "pressure_mb": 1015.0,
                    "pressure_in": 29.98,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 88,
                    "cloud": 12,
                    "feelslike_c": 17.7,
                    "feelslike_f": 63.9,
                    "windchill_c": 17.7,
                    "windchill_f": 63.9,
                    "heatindex_c": 17.7,
                    "heatindex_f": 63.9,
                    "dewpoint_c": 15.8,
                    "dewpoint_f": 60.4,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 8.9,
                    "gust_kph": 14.4,
                    "uv": 5.0
                },
                {
                    "time_epoch": 1686056400,
                    "time": "2023-06-06 08:00",
                    "temp_c": 19.4,
                    "temp_f": 66.9,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 4.7,
                    "wind_kph": 7.6,
                    "wind_degree": 61,
                    "wind_dir": "ENE",
                    "pressure_mb": 1016.0,
                    "pressure_in": 29.99,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 82,
                    "cloud": 8,
                    "feelslike_c": 19.4,
                    "feelslike_f": 66.9,
                    "windchill_c": 19.4,
                    "windchill_f": 66.9,
                    "heatindex_c": 19.4,
                    "heatindex_f": 66.9,
                    "dewpoint_c": 16.3,
                    "dewpoint_f": 61.3,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 6.7,
                    "gust_kph": 10.8,
                    "uv": 5.0
                },
                {
                    "time_epoch": 1686060000,
                    "time": "2023-06-06 09:00",
                    "temp_c": 21.7,
                    "temp_f": 71.1,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 4.9,
                    "wind_kph": 7.9,
                    "wind_degree": 69,
                    "wind_dir": "ENE",
                    "pressure_mb": 1015.0,
                    "pressure_in": 29.98,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 74,
                    "cloud": 6,
                    "feelslike_c": 21.7,
                    "feelslike_f": 71.1,
                    "windchill_c": 21.7,
                    "windchill_f": 71.1,
                    "heatindex_c": 24.5,
                    "heatindex_f": 76.1,
                    "dewpoint_c": 16.8,
                    "dewpoint_f": 62.2,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 5.8,
                    "gust_kph": 9.4,
                    "uv": 6.0
                },
                {
                    "time_epoch": 1686063600,
                    "time": "2023-06-06 10:00",
                    "temp_c": 23.9,
                    "temp_f": 75.0,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 4.7,
                    "wind_kph": 7.6,
                    "wind_degree": 67,
                    "wind_dir": "ENE",
                    "pressure_mb": 1015.0,
                    "pressure_in": 29.97,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 65,
                    "cloud": 9,
                    "feelslike_c": 25.5,
                    "feelslike_f": 77.9,
                    "windchill_c": 23.9,
                    "windchill_f": 75.0,
                    "heatindex_c": 25.5,
                    "heatindex_f": 77.9,
                    "dewpoint_c": 16.9,
                    "dewpoint_f": 62.4,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 5.4,
                    "gust_kph": 8.6,
                    "uv": 6.0
                },
                {
                    "time_epoch": 1686067200,
                    "time": "2023-06-06 11:00",
                    "temp_c": 27.7,
                    "temp_f": 81.9,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 4.5,
                    "wind_kph": 7.2,
                    "wind_degree": 88,
                    "wind_dir": "E",
                    "pressure_mb": 1015.0,
                    "pressure_in": 29.96,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 58,
                    "cloud": 16,
                    "feelslike_c": 29.1,
                    "feelslike_f": 84.4,
                    "windchill_c": 27.7,
                    "windchill_f": 81.9,
                    "heatindex_c": 29.1,
                    "heatindex_f": 84.4,
                    "dewpoint_c": 18.7,
                    "dewpoint_f": 65.7,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 5.1,
                    "gust_kph": 8.3,
                    "uv": 7.0
                },
                {
                    "time_epoch": 1686070800,
                    "time": "2023-06-06 12:00",
                    "temp_c": 28.8,
                    "temp_f": 83.8,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 4.3,
                    "wind_kph": 6.8,
                    "wind_degree": 97,
                    "wind_dir": "E",
                    "pressure_mb": 1015.0,
                    "pressure_in": 29.96,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 53,
                    "cloud": 17,
                    "feelslike_c": 30.1,
                    "feelslike_f": 86.2,
                    "windchill_c": 28.8,
                    "windchill_f": 83.8,
                    "heatindex_c": 30.1,
                    "heatindex_f": 86.2,
                    "dewpoint_c": 18.2,
                    "dewpoint_f": 64.8,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 4.9,
                    "gust_kph": 7.9,
                    "uv": 7.0
                },
                {
                    "time_epoch": 1686074400,
                    "time": "2023-06-06 13:00",
                    "temp_c": 29.9,
                    "temp_f": 85.8,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 3.8,
                    "wind_kph": 6.1,
                    "wind_degree": 89,
                    "wind_dir": "E",
                    "pressure_mb": 1014.0,
                    "pressure_in": 29.94,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 49,
                    "cloud": 17,
                    "feelslike_c": 31.1,
                    "feelslike_f": 88.0,
                    "windchill_c": 29.9,
                    "windchill_f": 85.8,
                    "heatindex_c": 31.1,
                    "heatindex_f": 88.0,
                    "dewpoint_c": 17.9,
                    "dewpoint_f": 64.2,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 4.5,
                    "gust_kph": 7.2,
                    "uv": 7.0
                },
                {
                    "time_epoch": 1686078000,
                    "time": "2023-06-06 14:00",
                    "temp_c": 32.4,
                    "temp_f": 90.3,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 4.3,
                    "wind_kph": 6.8,
                    "wind_degree": 71,
                    "wind_dir": "ENE",
                    "pressure_mb": 1013.0,
                    "pressure_in": 29.93,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 46,
                    "cloud": 12,
                    "feelslike_c": 34.7,
                    "feelslike_f": 94.5,
                    "windchill_c": 32.4,
                    "windchill_f": 90.3,
                    "heatindex_c": 34.7,
                    "heatindex_f": 94.5,
                    "dewpoint_c": 19.2,
                    "dewpoint_f": 66.6,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 4.9,
                    "gust_kph": 7.9,
                    "uv": 8.0
                },
                {
                    "time_epoch": 1686081600,
                    "time": "2023-06-06 15:00",
                    "temp_c": 32.8,
                    "temp_f": 91.0,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 4.9,
                    "wind_kph": 7.9,
                    "wind_degree": 61,
                    "wind_dir": "ENE",
                    "pressure_mb": 1013.0,
                    "pressure_in": 29.91,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 45,
                    "cloud": 7,
                    "feelslike_c": 35.1,
                    "feelslike_f": 95.2,
                    "windchill_c": 32.8,
                    "windchill_f": 91.0,
                    "heatindex_c": 35.1,
                    "heatindex_f": 95.2,
                    "dewpoint_c": 19.2,
                    "dewpoint_f": 66.6,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 5.6,
                    "gust_kph": 9.0,
                    "uv": 8.0
                },
                {
                    "time_epoch": 1686085200,
                    "time": "2023-06-06 16:00",
                    "temp_c": 32.9,
                    "temp_f": 91.2,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 5.6,
                    "wind_kph": 9.0,
                    "wind_degree": 54,
                    "wind_dir": "NE",
                    "pressure_mb": 1012.0,
                    "pressure_in": 29.89,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 45,
                    "cloud": 6,
                    "feelslike_c": 35.3,
                    "feelslike_f": 95.5,
                    "windchill_c": 32.9,
                    "windchill_f": 91.2,
                    "heatindex_c": 35.3,
                    "heatindex_f": 95.5,
                    "dewpoint_c": 19.2,
                    "dewpoint_f": 66.6,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 6.5,
                    "gust_kph": 10.4,
                    "uv": 8.0
                },
                {
                    "time_epoch": 1686088800,
                    "time": "2023-06-06 17:00",
                    "temp_c": 32.2,
                    "temp_f": 90.0,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 5.4,
                    "wind_kph": 8.6,
                    "wind_degree": 46,
                    "wind_dir": "NE",
                    "pressure_mb": 1012.0,
                    "pressure_in": 29.88,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 45,
                    "cloud": 8,
                    "feelslike_c": 34.2,
                    "feelslike_f": 93.6,
                    "windchill_c": 32.2,
                    "windchill_f": 90.0,
                    "heatindex_c": 34.2,
                    "heatindex_f": 93.6,
                    "dewpoint_c": 18.8,
                    "dewpoint_f": 65.8,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 6.3,
                    "gust_kph": 10.1,
                    "uv": 8.0
                },
                {
                    "time_epoch": 1686092400,
                    "time": "2023-06-06 18:00",
                    "temp_c": 30.7,
                    "temp_f": 87.3,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 4.9,
                    "wind_kph": 7.9,
                    "wind_degree": 33,
                    "wind_dir": "NNE",
                    "pressure_mb": 1011.0,
                    "pressure_in": 29.86,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 48,
                    "cloud": 10,
                    "feelslike_c": 32.2,
                    "feelslike_f": 90.0,
                    "windchill_c": 30.7,
                    "windchill_f": 87.3,
                    "heatindex_c": 32.2,
                    "heatindex_f": 90.0,
                    "dewpoint_c": 18.4,
                    "dewpoint_f": 65.1,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 5.6,
                    "gust_kph": 9.0,
                    "uv": 8.0
                },
                {
                    "time_epoch": 1686096000,
                    "time": "2023-06-06 19:00",
                    "temp_c": 29.1,
                    "temp_f": 84.4,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 4.5,
                    "wind_kph": 7.2,
                    "wind_degree": 37,
                    "wind_dir": "NE",
                    "pressure_mb": 1010.0,
                    "pressure_in": 29.83,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 56,
                    "cloud": 5,
                    "feelslike_c": 31.0,
                    "feelslike_f": 87.8,
                    "windchill_c": 29.1,
                    "windchill_f": 84.4,
                    "heatindex_c": 31.0,
                    "heatindex_f": 87.8,
                    "dewpoint_c": 19.6,
                    "dewpoint_f": 67.3,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 5.1,
                    "gust_kph": 8.3,
                    "uv": 7.0
                },
                {
                    "time_epoch": 1686099600,
                    "time": "2023-06-06 20:00",
                    "temp_c": 25.9,
                    "temp_f": 78.6,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 4.7,
                    "wind_kph": 7.6,
                    "wind_degree": 343,
                    "wind_dir": "NNW",
                    "pressure_mb": 1011.0,
                    "pressure_in": 29.86,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 63,
                    "cloud": 5,
                    "feelslike_c": 27.2,
                    "feelslike_f": 81.0,
                    "windchill_c": 25.9,
                    "windchill_f": 78.6,
                    "heatindex_c": 27.2,
                    "heatindex_f": 81.0,
                    "dewpoint_c": 18.2,
                    "dewpoint_f": 64.8,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 8.9,
                    "gust_kph": 14.4,
                    "uv": 7.0
                },
                {
                    "time_epoch": 1686103200,
                    "time": "2023-06-06 21:00",
                    "temp_c": 23.9,
                    "temp_f": 75.0,
                    "is_day": 0,
                    "condition": {
                        "text": "Clear",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                        "code": 1000
                    },
                    "wind_mph": 2.7,
                    "wind_kph": 4.3,
                    "wind_degree": 38,
                    "wind_dir": "NE",
                    "pressure_mb": 1011.0,
                    "pressure_in": 29.86,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 66,
                    "cloud": 5,
                    "feelslike_c": 25.5,
                    "feelslike_f": 77.9,
                    "windchill_c": 23.9,
                    "windchill_f": 75.0,
                    "heatindex_c": 25.5,
                    "heatindex_f": 77.9,
                    "dewpoint_c": 17.1,
                    "dewpoint_f": 62.8,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 5.6,
                    "gust_kph": 9.0,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686106800,
                    "time": "2023-06-06 22:00",
                    "temp_c": 23.0,
                    "temp_f": 73.4,
                    "is_day": 0,
                    "condition": {
                        "text": "Clear",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                        "code": 1000
                    },
                    "wind_mph": 2.2,
                    "wind_kph": 3.6,
                    "wind_degree": 96,
                    "wind_dir": "E",
                    "pressure_mb": 1012.0,
                    "pressure_in": 29.88,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 69,
                    "cloud": 6,
                    "feelslike_c": 25.0,
                    "feelslike_f": 77.0,
                    "windchill_c": 23.0,
                    "windchill_f": 73.4,
                    "heatindex_c": 25.0,
                    "heatindex_f": 77.0,
                    "dewpoint_c": 16.9,
                    "dewpoint_f": 62.4,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 4.7,
                    "gust_kph": 7.6,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686110400,
                    "time": "2023-06-06 23:00",
                    "temp_c": 22.4,
                    "temp_f": 72.3,
                    "is_day": 0,
                    "condition": {
                        "text": "Clear",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                        "code": 1000
                    },
                    "wind_mph": 2.7,
                    "wind_kph": 4.3,
                    "wind_degree": 58,
                    "wind_dir": "ENE",
                    "pressure_mb": 1012.0,
                    "pressure_in": 29.87,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 72,
                    "cloud": 6,
                    "feelslike_c": 24.7,
                    "feelslike_f": 76.5,
                    "windchill_c": 22.4,
                    "windchill_f": 72.3,
                    "heatindex_c": 24.7,
                    "heatindex_f": 76.5,
                    "dewpoint_c": 17.2,
                    "dewpoint_f": 63.0,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 5.6,
                    "gust_kph": 9.0,
                    "uv": 1.0
                }
            ]
        },
        {
            "date": "2023-06-07",
            "date_epoch": 1686096000,
            "day": {
                "maxtemp_c": 32.6,
                "maxtemp_f": 90.7,
                "mintemp_c": 18.4,
                "mintemp_f": 65.1,
                "avgtemp_c": 24.3,
                "avgtemp_f": 75.7,
                "maxwind_mph": 7.8,
                "maxwind_kph": 12.6,
                "totalprecip_mm": 2.4,
                "totalprecip_in": 0.09,
                "totalsnow_cm": 0.0,
                "avgvis_km": 10.0,
                "avgvis_miles": 6.0,
                "avghumidity": 67.0,
                "daily_will_it_rain": 1,
                "daily_chance_of_rain": 87,
                "daily_will_it_snow": 0,
                "daily_chance_of_snow": 0,
                "condition": {
                    "text": "Patchy rain possible",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                    "code": 1063
                },
                "uv": 5.0
            },
            "astro": {
                "sunrise": "06:07 AM",
                "sunset": "08:39 PM",
                "moonrise": "No moonrise",
                "moonset": "09:32 AM",
                "moon_phase": "Waning Gibbous",
                "moon_illumination": "89",
                "is_moon_up": 0,
                "is_sun_up": 1
            },
            "hour": [
                {
                    "time_epoch": 1686114000,
                    "time": "2023-06-07 00:00",
                    "temp_c": 21.4,
                    "temp_f": 70.5,
                    "is_day": 0,
                    "condition": {
                        "text": "Clear",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                        "code": 1000
                    },
                    "wind_mph": 2.9,
                    "wind_kph": 4.7,
                    "wind_degree": 18,
                    "wind_dir": "NNE",
                    "pressure_mb": 1012.0,
                    "pressure_in": 29.87,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 75,
                    "cloud": 6,
                    "feelslike_c": 21.4,
                    "feelslike_f": 70.5,
                    "windchill_c": 21.4,
                    "windchill_f": 70.5,
                    "heatindex_c": 24.4,
                    "heatindex_f": 75.9,
                    "dewpoint_c": 16.8,
                    "dewpoint_f": 62.2,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 6.0,
                    "gust_kph": 9.7,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686117600,
                    "time": "2023-06-07 01:00",
                    "temp_c": 20.6,
                    "temp_f": 69.1,
                    "is_day": 0,
                    "condition": {
                        "text": "Clear",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                        "code": 1000
                    },
                    "wind_mph": 1.8,
                    "wind_kph": 2.9,
                    "wind_degree": 284,
                    "wind_dir": "WNW",
                    "pressure_mb": 1012.0,
                    "pressure_in": 29.88,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 78,
                    "cloud": 6,
                    "feelslike_c": 20.6,
                    "feelslike_f": 69.1,
                    "windchill_c": 20.6,
                    "windchill_f": 69.1,
                    "heatindex_c": 20.6,
                    "heatindex_f": 69.1,
                    "dewpoint_c": 16.7,
                    "dewpoint_f": 62.1,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 3.8,
                    "gust_kph": 6.1,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686121200,
                    "time": "2023-06-07 02:00",
                    "temp_c": 20.0,
                    "temp_f": 68.0,
                    "is_day": 0,
                    "condition": {
                        "text": "Patchy rain possible",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                        "code": 1063
                    },
                    "wind_mph": 2.9,
                    "wind_kph": 4.7,
                    "wind_degree": 290,
                    "wind_dir": "WNW",
                    "pressure_mb": 1012.0,
                    "pressure_in": 29.89,
                    "precip_mm": 0.1,
                    "precip_in": 0.0,
                    "humidity": 81,
                    "cloud": 73,
                    "feelslike_c": 20.0,
                    "feelslike_f": 68.0,
                    "windchill_c": 20.0,
                    "windchill_f": 68.0,
                    "heatindex_c": 20.0,
                    "heatindex_f": 68.0,
                    "dewpoint_c": 16.6,
                    "dewpoint_f": 61.9,
                    "will_it_rain": 0,
                    "chance_of_rain": 62,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 6.0,
                    "gust_kph": 9.7,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686124800,
                    "time": "2023-06-07 03:00",
                    "temp_c": 19.7,
                    "temp_f": 67.5,
                    "is_day": 0,
                    "condition": {
                        "text": "Patchy rain possible",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                        "code": 1063
                    },
                    "wind_mph": 3.6,
                    "wind_kph": 5.8,
                    "wind_degree": 342,
                    "wind_dir": "NNW",
                    "pressure_mb": 1012.0,
                    "pressure_in": 29.88,
                    "precip_mm": 0.1,
                    "precip_in": 0.0,
                    "humidity": 82,
                    "cloud": 81,
                    "feelslike_c": 19.7,
                    "feelslike_f": 67.5,
                    "windchill_c": 19.7,
                    "windchill_f": 67.5,
                    "heatindex_c": 19.7,
                    "heatindex_f": 67.5,
                    "dewpoint_c": 16.5,
                    "dewpoint_f": 61.7,
                    "will_it_rain": 1,
                    "chance_of_rain": 83,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 7.6,
                    "gust_kph": 12.2,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686128400,
                    "time": "2023-06-07 04:00",
                    "temp_c": 19.4,
                    "temp_f": 66.9,
                    "is_day": 0,
                    "condition": {
                        "text": "Patchy rain possible",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                        "code": 1063
                    },
                    "wind_mph": 3.4,
                    "wind_kph": 5.4,
                    "wind_degree": 324,
                    "wind_dir": "NW",
                    "pressure_mb": 1012.0,
                    "pressure_in": 29.89,
                    "precip_mm": 0.2,
                    "precip_in": 0.01,
                    "humidity": 83,
                    "cloud": 86,
                    "feelslike_c": 19.4,
                    "feelslike_f": 66.9,
                    "windchill_c": 19.4,
                    "windchill_f": 66.9,
                    "heatindex_c": 19.4,
                    "heatindex_f": 66.9,
                    "dewpoint_c": 16.3,
                    "dewpoint_f": 61.3,
                    "will_it_rain": 0,
                    "chance_of_rain": 62,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 6.9,
                    "gust_kph": 11.2,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686132000,
                    "time": "2023-06-07 05:00",
                    "temp_c": 19.0,
                    "temp_f": 66.2,
                    "is_day": 0,
                    "condition": {
                        "text": "Clear",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                        "code": 1000
                    },
                    "wind_mph": 3.4,
                    "wind_kph": 5.4,
                    "wind_degree": 327,
                    "wind_dir": "NNW",
                    "pressure_mb": 1012.0,
                    "pressure_in": 29.89,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 84,
                    "cloud": 7,
                    "feelslike_c": 19.0,
                    "feelslike_f": 66.2,
                    "windchill_c": 19.0,
                    "windchill_f": 66.2,
                    "heatindex_c": 19.0,
                    "heatindex_f": 66.2,
                    "dewpoint_c": 16.2,
                    "dewpoint_f": 61.2,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 6.9,
                    "gust_kph": 11.2,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686135600,
                    "time": "2023-06-07 06:00",
                    "temp_c": 18.4,
                    "temp_f": 65.1,
                    "is_day": 0,
                    "condition": {
                        "text": "Patchy rain possible",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                        "code": 1063
                    },
                    "wind_mph": 3.4,
                    "wind_kph": 5.4,
                    "wind_degree": 350,
                    "wind_dir": "N",
                    "pressure_mb": 1012.0,
                    "pressure_in": 29.89,
                    "precip_mm": 0.1,
                    "precip_in": 0.0,
                    "humidity": 86,
                    "cloud": 89,
                    "feelslike_c": 18.4,
                    "feelslike_f": 65.1,
                    "windchill_c": 18.4,
                    "windchill_f": 65.1,
                    "heatindex_c": 18.4,
                    "heatindex_f": 65.1,
                    "dewpoint_c": 15.9,
                    "dewpoint_f": 60.6,
                    "will_it_rain": 1,
                    "chance_of_rain": 80,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 6.9,
                    "gust_kph": 11.2,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686139200,
                    "time": "2023-06-07 07:00",
                    "temp_c": 18.9,
                    "temp_f": 66.0,
                    "is_day": 1,
                    "condition": {
                        "text": "Patchy rain possible",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063
                    },
                    "wind_mph": 3.1,
                    "wind_kph": 5.0,
                    "wind_degree": 3,
                    "wind_dir": "N",
                    "pressure_mb": 1013.0,
                    "pressure_in": 29.9,
                    "precip_mm": 0.1,
                    "precip_in": 0.0,
                    "humidity": 85,
                    "cloud": 86,
                    "feelslike_c": 18.9,
                    "feelslike_f": 66.0,
                    "windchill_c": 18.9,
                    "windchill_f": 66.0,
                    "heatindex_c": 18.9,
                    "heatindex_f": 66.0,
                    "dewpoint_c": 16.2,
                    "dewpoint_f": 61.2,
                    "will_it_rain": 1,
                    "chance_of_rain": 87,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 6.3,
                    "gust_kph": 10.1,
                    "uv": 4.0
                },
                {
                    "time_epoch": 1686142800,
                    "time": "2023-06-07 08:00",
                    "temp_c": 20.7,
                    "temp_f": 69.3,
                    "is_day": 1,
                    "condition": {
                        "text": "Patchy rain possible",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063
                    },
                    "wind_mph": 3.1,
                    "wind_kph": 5.0,
                    "wind_degree": 348,
                    "wind_dir": "NNW",
                    "pressure_mb": 1013.0,
                    "pressure_in": 29.9,
                    "precip_mm": 0.2,
                    "precip_in": 0.01,
                    "humidity": 79,
                    "cloud": 81,
                    "feelslike_c": 20.7,
                    "feelslike_f": 69.3,
                    "windchill_c": 20.7,
                    "windchill_f": 69.3,
                    "heatindex_c": 20.7,
                    "heatindex_f": 69.3,
                    "dewpoint_c": 16.9,
                    "dewpoint_f": 62.4,
                    "will_it_rain": 1,
                    "chance_of_rain": 72,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 4.7,
                    "gust_kph": 7.6,
                    "uv": 5.0
                },
                {
                    "time_epoch": 1686146400,
                    "time": "2023-06-07 09:00",
                    "temp_c": 22.6,
                    "temp_f": 72.7,
                    "is_day": 1,
                    "condition": {
                        "text": "Patchy rain possible",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063
                    },
                    "wind_mph": 2.9,
                    "wind_kph": 4.7,
                    "wind_degree": 348,
                    "wind_dir": "NNW",
                    "pressure_mb": 1013.0,
                    "pressure_in": 29.9,
                    "precip_mm": 0.1,
                    "precip_in": 0.0,
                    "humidity": 71,
                    "cloud": 72,
                    "feelslike_c": 24.8,
                    "feelslike_f": 76.6,
                    "windchill_c": 22.6,
                    "windchill_f": 72.7,
                    "heatindex_c": 24.8,
                    "heatindex_f": 76.6,
                    "dewpoint_c": 17.1,
                    "dewpoint_f": 62.8,
                    "will_it_rain": 1,
                    "chance_of_rain": 76,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 3.6,
                    "gust_kph": 5.8,
                    "uv": 5.0
                },
                {
                    "time_epoch": 1686150000,
                    "time": "2023-06-07 10:00",
                    "temp_c": 24.8,
                    "temp_f": 76.6,
                    "is_day": 1,
                    "condition": {
                        "text": "Patchy rain possible",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063
                    },
                    "wind_mph": 3.1,
                    "wind_kph": 5.0,
                    "wind_degree": 358,
                    "wind_dir": "N",
                    "pressure_mb": 1012.0,
                    "pressure_in": 29.89,
                    "precip_mm": 0.2,
                    "precip_in": 0.01,
                    "humidity": 63,
                    "cloud": 87,
                    "feelslike_c": 26.1,
                    "feelslike_f": 79.0,
                    "windchill_c": 24.8,
                    "windchill_f": 76.6,
                    "heatindex_c": 26.1,
                    "heatindex_f": 79.0,
                    "dewpoint_c": 17.2,
                    "dewpoint_f": 63.0,
                    "will_it_rain": 0,
                    "chance_of_rain": 60,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 3.6,
                    "gust_kph": 5.8,
                    "uv": 5.0
                },
                {
                    "time_epoch": 1686153600,
                    "time": "2023-06-07 11:00",
                    "temp_c": 30.0,
                    "temp_f": 86.0,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 2.9,
                    "wind_kph": 4.7,
                    "wind_degree": 341,
                    "wind_dir": "NNW",
                    "pressure_mb": 1012.0,
                    "pressure_in": 29.88,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 56,
                    "cloud": 11,
                    "feelslike_c": 32.3,
                    "feelslike_f": 90.1,
                    "windchill_c": 30.0,
                    "windchill_f": 86.0,
                    "heatindex_c": 32.3,
                    "heatindex_f": 90.1,
                    "dewpoint_c": 20.1,
                    "dewpoint_f": 68.2,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 3.4,
                    "gust_kph": 5.4,
                    "uv": 8.0
                },
                {
                    "time_epoch": 1686157200,
                    "time": "2023-06-07 12:00",
                    "temp_c": 31.4,
                    "temp_f": 88.5,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 3.6,
                    "wind_kph": 5.8,
                    "wind_degree": 353,
                    "wind_dir": "N",
                    "pressure_mb": 1012.0,
                    "pressure_in": 29.87,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 50,
                    "cloud": 13,
                    "feelslike_c": 33.9,
                    "feelslike_f": 93.0,
                    "windchill_c": 31.4,
                    "windchill_f": 88.5,
                    "heatindex_c": 33.9,
                    "heatindex_f": 93.0,
                    "dewpoint_c": 19.8,
                    "dewpoint_f": 67.6,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 4.3,
                    "gust_kph": 6.8,
                    "uv": 8.0
                },
                {
                    "time_epoch": 1686160800,
                    "time": "2023-06-07 13:00",
                    "temp_c": 32.6,
                    "temp_f": 90.7,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 3.6,
                    "wind_kph": 5.8,
                    "wind_degree": 11,
                    "wind_dir": "NNE",
                    "pressure_mb": 1011.0,
                    "pressure_in": 29.85,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 46,
                    "cloud": 13,
                    "feelslike_c": 35.1,
                    "feelslike_f": 95.2,
                    "windchill_c": 32.6,
                    "windchill_f": 90.7,
                    "heatindex_c": 35.1,
                    "heatindex_f": 95.2,
                    "dewpoint_c": 19.5,
                    "dewpoint_f": 67.1,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 4.0,
                    "gust_kph": 6.5,
                    "uv": 8.0
                },
                {
                    "time_epoch": 1686164400,
                    "time": "2023-06-07 14:00",
                    "temp_c": 31.4,
                    "temp_f": 88.5,
                    "is_day": 1,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "wind_mph": 3.1,
                    "wind_kph": 5.0,
                    "wind_degree": 19,
                    "wind_dir": "NNE",
                    "pressure_mb": 1010.0,
                    "pressure_in": 29.83,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 43,
                    "cloud": 19,
                    "feelslike_c": 32.6,
                    "feelslike_f": 90.7,
                    "windchill_c": 31.4,
                    "windchill_f": 88.5,
                    "heatindex_c": 32.6,
                    "heatindex_f": 90.7,
                    "dewpoint_c": 17.5,
                    "dewpoint_f": 63.5,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 3.6,
                    "gust_kph": 5.8,
                    "uv": 8.0
                },
                {
                    "time_epoch": 1686168000,
                    "time": "2023-06-07 15:00",
                    "temp_c": 31.0,
                    "temp_f": 87.8,
                    "is_day": 1,
                    "condition": {
                        "text": "Partly cloudy",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                        "code": 1003
                    },
                    "wind_mph": 3.6,
                    "wind_kph": 5.8,
                    "wind_degree": 25,
                    "wind_dir": "NNE",
                    "pressure_mb": 1009.0,
                    "pressure_in": 29.81,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 44,
                    "cloud": 41,
                    "feelslike_c": 32.0,
                    "feelslike_f": 89.6,
                    "windchill_c": 31.0,
                    "windchill_f": 87.8,
                    "heatindex_c": 32.0,
                    "heatindex_f": 89.6,
                    "dewpoint_c": 17.2,
                    "dewpoint_f": 63.0,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 4.0,
                    "gust_kph": 6.5,
                    "uv": 8.0
                },
                {
                    "time_epoch": 1686171600,
                    "time": "2023-06-07 16:00",
                    "temp_c": 30.1,
                    "temp_f": 86.2,
                    "is_day": 1,
                    "condition": {
                        "text": "Partly cloudy",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                        "code": 1003
                    },
                    "wind_mph": 4.3,
                    "wind_kph": 6.8,
                    "wind_degree": 30,
                    "wind_dir": "NNE",
                    "pressure_mb": 1009.0,
                    "pressure_in": 29.8,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 47,
                    "cloud": 46,
                    "feelslike_c": 31.2,
                    "feelslike_f": 88.2,
                    "windchill_c": 30.1,
                    "windchill_f": 86.2,
                    "heatindex_c": 31.2,
                    "heatindex_f": 88.2,
                    "dewpoint_c": 17.5,
                    "dewpoint_f": 63.5,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 4.9,
                    "gust_kph": 7.9,
                    "uv": 8.0
                },
                {
                    "time_epoch": 1686175200,
                    "time": "2023-06-07 17:00",
                    "temp_c": 28.6,
                    "temp_f": 83.5,
                    "is_day": 1,
                    "condition": {
                        "text": "Partly cloudy",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                        "code": 1003
                    },
                    "wind_mph": 2.9,
                    "wind_kph": 4.7,
                    "wind_degree": 48,
                    "wind_dir": "NE",
                    "pressure_mb": 1009.0,
                    "pressure_in": 29.79,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 52,
                    "cloud": 42,
                    "feelslike_c": 29.7,
                    "feelslike_f": 85.5,
                    "windchill_c": 28.6,
                    "windchill_f": 83.5,
                    "heatindex_c": 29.7,
                    "heatindex_f": 85.5,
                    "dewpoint_c": 17.9,
                    "dewpoint_f": 64.2,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 4.0,
                    "gust_kph": 6.5,
                    "uv": 7.0
                },
                {
                    "time_epoch": 1686178800,
                    "time": "2023-06-07 18:00",
                    "temp_c": 27.2,
                    "temp_f": 81.0,
                    "is_day": 1,
                    "condition": {
                        "text": "Patchy rain possible",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063
                    },
                    "wind_mph": 3.6,
                    "wind_kph": 5.8,
                    "wind_degree": 124,
                    "wind_dir": "SE",
                    "pressure_mb": 1008.0,
                    "pressure_in": 29.78,
                    "precip_mm": 0.1,
                    "precip_in": 0.0,
                    "humidity": 58,
                    "cloud": 86,
                    "feelslike_c": 28.4,
                    "feelslike_f": 83.1,
                    "windchill_c": 27.2,
                    "windchill_f": 81.0,
                    "heatindex_c": 28.4,
                    "heatindex_f": 83.1,
                    "dewpoint_c": 18.1,
                    "dewpoint_f": 64.6,
                    "will_it_rain": 1,
                    "chance_of_rain": 78,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 5.1,
                    "gust_kph": 8.3,
                    "uv": 6.0
                },
                {
                    "time_epoch": 1686182400,
                    "time": "2023-06-07 19:00",
                    "temp_c": 25.9,
                    "temp_f": 78.6,
                    "is_day": 1,
                    "condition": {
                        "text": "Patchy rain possible",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063
                    },
                    "wind_mph": 6.9,
                    "wind_kph": 11.2,
                    "wind_degree": 130,
                    "wind_dir": "SE",
                    "pressure_mb": 1008.0,
                    "pressure_in": 29.76,
                    "precip_mm": 0.5,
                    "precip_in": 0.02,
                    "humidity": 65,
                    "cloud": 74,
                    "feelslike_c": 27.4,
                    "feelslike_f": 81.3,
                    "windchill_c": 25.9,
                    "windchill_f": 78.6,
                    "heatindex_c": 27.4,
                    "heatindex_f": 81.3,
                    "dewpoint_c": 18.9,
                    "dewpoint_f": 66.0,
                    "will_it_rain": 0,
                    "chance_of_rain": 67,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 9.0,
                    "vis_miles": 5.0,
                    "gust_mph": 11.6,
                    "gust_kph": 18.7,
                    "uv": 6.0
                },
                {
                    "time_epoch": 1686186000,
                    "time": "2023-06-07 20:00",
                    "temp_c": 23.5,
                    "temp_f": 74.3,
                    "is_day": 1,
                    "condition": {
                        "text": "Patchy rain possible",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063
                    },
                    "wind_mph": 7.8,
                    "wind_kph": 12.6,
                    "wind_degree": 167,
                    "wind_dir": "SSE",
                    "pressure_mb": 1008.0,
                    "pressure_in": 29.78,
                    "precip_mm": 0.1,
                    "precip_in": 0.0,
                    "humidity": 72,
                    "cloud": 75,
                    "feelslike_c": 25.3,
                    "feelslike_f": 77.5,
                    "windchill_c": 23.5,
                    "windchill_f": 74.3,
                    "heatindex_c": 25.3,
                    "heatindex_f": 77.5,
                    "dewpoint_c": 18.1,
                    "dewpoint_f": 64.6,
                    "will_it_rain": 1,
                    "chance_of_rain": 80,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 16.3,
                    "gust_kph": 26.3,
                    "uv": 5.0
                },
                {
                    "time_epoch": 1686189600,
                    "time": "2023-06-07 21:00",
                    "temp_c": 22.3,
                    "temp_f": 72.1,
                    "is_day": 0,
                    "condition": {
                        "text": "Clear",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                        "code": 1000
                    },
                    "wind_mph": 3.8,
                    "wind_kph": 6.1,
                    "wind_degree": 186,
                    "wind_dir": "S",
                    "pressure_mb": 1009.0,
                    "pressure_in": 29.78,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 71,
                    "cloud": 7,
                    "feelslike_c": 24.7,
                    "feelslike_f": 76.5,
                    "windchill_c": 22.3,
                    "windchill_f": 72.1,
                    "heatindex_c": 24.7,
                    "heatindex_f": 76.5,
                    "dewpoint_c": 16.7,
                    "dewpoint_f": 62.1,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 8.1,
                    "gust_kph": 13.0,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686193200,
                    "time": "2023-06-07 22:00",
                    "temp_c": 21.2,
                    "temp_f": 70.2,
                    "is_day": 0,
                    "condition": {
                        "text": "Moderate rain at times",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/299.png",
                        "code": 1186
                    },
                    "wind_mph": 3.8,
                    "wind_kph": 6.1,
                    "wind_degree": 253,
                    "wind_dir": "WSW",
                    "pressure_mb": 1010.0,
                    "pressure_in": 29.81,
                    "precip_mm": 0.6,
                    "precip_in": 0.02,
                    "humidity": 76,
                    "cloud": 88,
                    "feelslike_c": 21.2,
                    "feelslike_f": 70.2,
                    "windchill_c": 21.2,
                    "windchill_f": 70.2,
                    "heatindex_c": 24.3,
                    "heatindex_f": 75.7,
                    "dewpoint_c": 16.8,
                    "dewpoint_f": 62.2,
                    "will_it_rain": 1,
                    "chance_of_rain": 83,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 8.1,
                    "gust_kph": 13.0,
                    "uv": 1.0
                },
                {
                    "time_epoch": 1686196800,
                    "time": "2023-06-07 23:00",
                    "temp_c": 21.4,
                    "temp_f": 70.5,
                    "is_day": 0,
                    "condition": {
                        "text": "Clear",
                        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                        "code": 1000
                    },
                    "wind_mph": 3.6,
                    "wind_kph": 5.8,
                    "wind_degree": 289,
                    "wind_dir": "WNW",
                    "pressure_mb": 1010.0,
                    "pressure_in": 29.81,
                    "precip_mm": 0.0,
                    "precip_in": 0.0,
                    "humidity": 74,
                    "cloud": 6,
                    "feelslike_c": 21.4,
                    "feelslike_f": 70.5,
                    "windchill_c": 21.4,
                    "windchill_f": 70.5,
                    "heatindex_c": 24.4,
                    "heatindex_f": 75.9,
                    "dewpoint_c": 16.7,
                    "dewpoint_f": 62.1,
                    "will_it_rain": 0,
                    "chance_of_rain": 0,
                    "will_it_snow": 0,
                    "chance_of_snow": 0,
                    "vis_km": 10.0,
                    "vis_miles": 6.0,
                    "gust_mph": 7.6,
                    "gust_kph": 12.2,
                    "uv": 1.0
                }
            ]
        }
    ]
}
